name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.2.10
    - name: Install missing libs
      run: |
        sudo apt-get -yqq install libsqlite3-dev
    - name: Install gems
			env:
				RAILS_VERSION: "4.2"
      run: |
        gem uninstall -aIx bundler
        gem install bundler -v 1.17.3
        bundle install --jobs 4 --retry 3
    - name: Test
      run: |
        bundle exec rake
