name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.2.10
    - name: Install gems
      run: |
        gem install bundler -v 1.13.7
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Build and test with Rake
      run: |
        bundle exec rake
